version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "cat-gpt-slack-bot"

[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "cat-gpt-slack-bot"
region = "ap-northeast-1"
profile = "slack-bot"
image_repositories = []

[default.sync.parameters]
watch = true
beta_features = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false
